esphome:
  name: sp4ce-button
  platform: ESP8266
  board: esp01_1m

logger:

api:
  password: !secret api_password

ota:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

light:
  - platform: fastled_clockless
    id: led
    chipset: WS2812B
    pin: 2
    num_leds: 3
    rgb_order: GRB
    restore_mode: ALWAYS_OFF
    effects:
      - addressable_rainbow:
          name: rainbow
          speed: 100
          width: 3

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: 4
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 20ms
    on_state:
      then:
        - lambda: |-
            id(mqtt_client).publish("bus/devices/opener.button/event", x ? "down" : "up");
    on_press:
      then:
        - light.turn_off:
            id: led
        - light.turn_on:
            id: led
            red: 0
            green: 1
            blue: 0
            brightness: 1
            transition_length: 400ms
        - delay: 1500ms
        - light.turn_off:
            id: led
            transition_length: 400ms

mqtt:
  id: mqtt_client
  broker: !secret mqtt_broker
  discovery: false
  topic_prefix: bus/devices/opener.button
  username: !secret mqtt_username
  password: !secret mqtt_password
  on_message:
    - topic: bus/devices/opener.button/rainbow
      payload: 'on'
      then: 
        - light.turn_on:
            id: led
            brightness: 1
            effect: rainbow
    - topic: bus/devices/opener.button/rainbow
      payload: 'off'
      then: 
        - light.turn_off:
            id: led
            transition_length: 400ms